# Generated by Django 5.1.4 on 2026-06-30 04:02

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_class_section_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="school_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="school_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="attendancesession",
            name="image",
            field=models.ImageField(
                upload_to=attendance.models.scoped_attendance_image_path
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="image",
            field=models.ImageField(
                upload_to=attendance.models.scoped_student_image_path
            ),
        ),
    ]
