# Generated by Django 5.1.4 on 2026-06-30 05:43

import attendance.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0003_attendancesession_school_code_student_school_code_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSessionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=attendance.models.scoped_attendance_session_image_path
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="attendance.attendancesession",
                    ),
                ),
            ],
        ),
    ]
